### ISSUE TITLE
invalid install.xml file.

### ISSUE THREAD

**Issue by danmarsden** [pawanwiziq/moodlenew-mod_wiziq#11]
install.xml is no longer valid (created for an old version of Moodle) - If interested in supporting TotaraLMS this file will also trigger unit test failures preventing a site from deploying your plugin to TotaraLMS.

This needs to be fixed using the Moodle xmldb editor (under admin > development > XMLDB.)

Please hit the "load" link for the wiziq install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

**Comment by pawanwiziq** [comment]
Fixed

**Comment by danmarsden** [comment]
you have not used the built in xmldb editor to modify or update this file and I can still see a number of issues This is not fixed.

**Comment by danmarsden** [comment]
download_details and recording_details are also invalid table names inside your plugin - they need to be prefixed with wiziq_

**Comment by danmarsden** [comment]
still looks like someone is hand-rolling the xmldb file and this has not been fixed correctly. please see comment #1 above that explains how to use xmldb editor to fix this file.
