### ISSUE TITLE
hard coded check against "student" role shortname

### ISSUE THREAD

**Issue by danmarsden** [pawanwiziq/moodlenew-mod_wiziq#2]
Many sites customise the roles and do not use the standard "student" role at all. You should be defining new capabilities in this plugin which are given by default to the student role, and then making a has_capability check against your custom capapbility.

**Comment by pawanwiziq** [comment]
Fixed

**Comment by danmarsden** [comment]
I still see a lot of commented out code referring to isstudent - I suspblect you also need to be checking that students have a certain capability for some actions. Otherwise "guest" users may be able to do things they should not be able to?
