### ISSUE TITLE
incorrect use of CURL

### ISSUE THREAD

**Issue by danmarsden** [pawanwiziq/moodlenew-mod_wiziq#5]
There are a few places in your code that do this - here's one:
https://github.com/pawanwiziq/moodlenew-mod_wiziq/blob/6ba221fa7bacda8c3ecc4074e6c66d727ba837ff/locallib.php#L169

Directly calling the PHP curl functions like this is not allowed - you should be using the core Moodle curl class. Many sites are hosted behind proxies and the Moodle curl class allows the site admin to configure various settings. Please convert these to using the correct Moodle curl class.

**Comment by pawanwiziq** [comment]
Fixed

**Comment by danmarsden** [comment]
I can still see curl_init() being used in the code here on github.
